"""
Fallback accounting configuration when `accounting_defaults/*.json` is absent.

Prefer bundled JSON (or export from your live DB). See `accounting_defaults/README.md`.
"""

# (event_type, system_tag, direction, description, trigger_type)
TRANSACTION_TEMPLATE_TUPLES: list[tuple[str, str, str, str, str]] = [
    ("LOAN_APPROVAL", "loan_principal", "DEBIT", "Creation of Loan - Principal", "EVENT"),
    ("LOAN_APPROVAL", "cash_operating", "CREDIT", "Creation of Loan - Disbursed Amount", "EVENT"),
    ("LOAN_APPROVAL", "deferred_fee_liability", "CREDIT", "Creation of Loan - Fees", "EVENT"),
    ("FEE_AMORTISATION_DRAWDOWN", "deferred_fee_liability", "DEBIT", "Amortisation of drawdown fees", "EOM"),
    ("FEE_AMORTISATION_DRAWDOWN", "deferred_fee_income", "CREDIT", "Amortisation of drawdown fees", "EOM"),
    ("FEE_AMORTISATION_ARRANGEMENT", "deferred_fee_liability", "DEBIT", "Amortisation of arrangement fees", "EOM"),
    ("FEE_AMORTISATION_ARRANGEMENT", "deferred_fee_income", "CREDIT", "Amortisation of arrangement fees", "EOM"),
    ("FEE_AMORTISATION_ADMIN", "deferred_fee_liability", "DEBIT", "Amortisation of administration fees", "EOM"),
    ("FEE_AMORTISATION_ADMIN", "deferred_fee_income", "CREDIT", "Amortisation of administration fees", "EOM"),
    ("BILLING_PRINCIPAL_ARREARS", "principal_arrears", "DEBIT", "Billing of principal arrears", "EOD"),
    ("BILLING_PRINCIPAL_ARREARS", "loan_principal", "CREDIT", "Billing of principal arrears", "EOD"),
    ("PAYMENT_PRINCIPAL", "cash_operating", "DEBIT", "Payment of principal", "EVENT"),
    ("PAYMENT_PRINCIPAL", "principal_arrears", "CREDIT", "Payment of principal", "EVENT"),
    ("PAYMENT_PRINCIPAL_NOT_YET_DUE", "cash_operating", "DEBIT", "Direct payment of principal not yet due", "EVENT"),
    ("PAYMENT_PRINCIPAL_NOT_YET_DUE", "loan_principal", "CREDIT", "Direct payment of principal not yet due", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_PRINCIPAL_ARREARS", "unapplied_funds", "DEBIT", "Unapplied liquidation: principal arrears", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_PRINCIPAL_ARREARS", "principal_arrears", "CREDIT", "Unapplied liquidation: principal arrears", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_PRINCIPAL_NOT_YET_DUE", "unapplied_funds", "DEBIT", "Unapplied liquidation: principal not yet due", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_PRINCIPAL_NOT_YET_DUE", "loan_principal", "CREDIT", "Unapplied liquidation: principal not yet due", "EVENT"),
    ("ACCRUAL_REGULAR_INTEREST", "regular_interest_accrued", "DEBIT", "Accrual of REGULAR interest", "EOD"),
    ("ACCRUAL_REGULAR_INTEREST", "regular_interest_income_holding", "CREDIT", "Accrual of REGULAR interest", "EOD"),
    ("ACCRUAL_PENALTY_INTEREST", "penalty_interest_asset", "DEBIT", "Daily penalty interest accrual (11)", "EOD"),
    ("ACCRUAL_PENALTY_INTEREST", "penalty_interest_suspense", "CREDIT", "Daily penalty interest accrual (11)", "EOD"),
    ("ACCRUAL_DEFAULT_INTEREST", "default_interest_asset", "DEBIT", "Daily default interest accrual (14)", "EOD"),
    ("ACCRUAL_DEFAULT_INTEREST", "default_interest_suspense", "CREDIT", "Daily default interest accrual (14)", "EOD"),
    ("CLEAR_DAILY_ACCRUAL", "regular_interest_income_holding", "DEBIT", "Clear the Daily Accrual Accounts", "EOD"),
    ("CLEAR_DAILY_ACCRUAL", "regular_interest_accrued", "CREDIT", "Clear the Daily Accrual Accounts", "EOD"),
    ("BILLING_REGULAR_INTEREST", "regular_interest_arrears", "DEBIT", "Billing of REGULAR interest arrears", "EOD"),
    ("BILLING_REGULAR_INTEREST", "regular_interest_income", "CREDIT", "Billing of REGULAR interest arrears", "EOD"),
    ("PAYMENT_REGULAR_INTEREST", "cash_operating", "DEBIT", "Payment of REGULAR interest", "EVENT"),
    ("PAYMENT_REGULAR_INTEREST", "regular_interest_arrears", "CREDIT", "Payment of REGULAR interest", "EVENT"),
    ("PAYMENT_REGULAR_INTEREST_NOT_YET_DUE", "cash_operating", "DEBIT", "Direct payment of regular interest not yet due", "EVENT"),
    ("PAYMENT_REGULAR_INTEREST_NOT_YET_DUE", "regular_interest_accrued", "CREDIT", "Direct payment of regular interest not yet due", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_REGULAR_INTEREST", "unapplied_funds", "DEBIT", "Unapplied liquidation: regular interest arrears", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_REGULAR_INTEREST", "regular_interest_arrears", "CREDIT", "Unapplied liquidation: regular interest arrears", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_REGULAR_INTEREST_NOT_YET_DUE", "unapplied_funds", "DEBIT", "Unapplied liquidation: regular interest accrued", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_REGULAR_INTEREST_NOT_YET_DUE", "regular_interest_accrued", "CREDIT", "Unapplied liquidation: regular interest accrued", "EVENT"),
    ("PAYMENT_PENALTY_INTEREST", "cash_operating", "DEBIT", "Payment of penalty interest (12)", "EVENT"),
    ("PAYMENT_PENALTY_INTEREST", "penalty_interest_asset", "CREDIT", "Payment of penalty interest (12)", "EVENT"),
    ("PAYMENT_PENALTY_INTEREST", "penalty_interest_suspense", "DEBIT", "Recognise penalty income (12a)", "EVENT"),
    ("PAYMENT_PENALTY_INTEREST", "penalty_interest_income", "CREDIT", "Recognise penalty income (12a)", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_PENALTY_INTEREST", "unapplied_funds", "DEBIT", "Unapplied liquidation: penalty interest (12)", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_PENALTY_INTEREST", "penalty_interest_asset", "CREDIT", "Unapplied liquidation: penalty interest (12)", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_PENALTY_INTEREST", "penalty_interest_suspense", "DEBIT", "Unapplied liquidation: recognise penalty income (12a)", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_PENALTY_INTEREST", "penalty_interest_income", "CREDIT", "Unapplied liquidation: recognise penalty income (12a)", "EVENT"),
    ("REVERSAL_PENALTY_INTEREST", "penalty_interest_income", "DEBIT", "Reversal of penalty interest", "EVENT"),
    ("REVERSAL_PENALTY_INTEREST", "penalty_interest_asset", "CREDIT", "Reversal of penalty interest", "EVENT"),
    ("PAYMENT_DEFAULT_INTEREST", "cash_operating", "DEBIT", "Payment of default interest (15)", "EVENT"),
    ("PAYMENT_DEFAULT_INTEREST", "default_interest_asset", "CREDIT", "Payment of default interest (15)", "EVENT"),
    ("PAYMENT_DEFAULT_INTEREST", "default_interest_suspense", "DEBIT", "Recognise default income (15a)", "EVENT"),
    ("PAYMENT_DEFAULT_INTEREST", "default_interest_income", "CREDIT", "Recognise default income (15a)", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_DEFAULT_INTEREST", "unapplied_funds", "DEBIT", "Unapplied liquidation: default interest (15)", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_DEFAULT_INTEREST", "default_interest_asset", "CREDIT", "Unapplied liquidation: default interest (15)", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_DEFAULT_INTEREST", "default_interest_suspense", "DEBIT", "Unapplied liquidation: recognise default income (15a)", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_DEFAULT_INTEREST", "default_interest_income", "CREDIT", "Unapplied liquidation: recognise default income (15a)", "EVENT"),
    ("REVERSAL_DEFAULT_INTEREST", "default_interest_income", "DEBIT", "Reversal of default interest", "EVENT"),
    ("REVERSAL_DEFAULT_INTEREST", "default_interest_asset", "CREDIT", "Reversal of default interest", "EVENT"),
    ("ACCRUAL_REGULAR_INTEREST_SUSPENSE", "regular_interest_accrued", "DEBIT", "Daily accrual of regular interest into suspense", "EOD"),
    ("ACCRUAL_REGULAR_INTEREST_SUSPENSE", "regular_interest_suspense", "CREDIT", "Daily accrual of regular interest into suspense", "EOD"),
    ("PAYMENT_REGULAR_INTEREST_SUSPENSE", "cash_operating", "DEBIT", "Payment of regular interest in suspense", "EVENT"),
    ("PAYMENT_REGULAR_INTEREST_SUSPENSE", "regular_interest_suspense", "CREDIT", "Payment of regular interest in suspense", "EVENT"),
    ("PAYMENT_REGULAR_INTEREST_ACCRUED", "cash_operating", "DEBIT", "Payment of regular interest accrued (unbilled)", "EVENT"),
    ("PAYMENT_REGULAR_INTEREST_ACCRUED", "regular_interest_accrued", "CREDIT", "Payment of regular interest accrued (unbilled)", "EVENT"),
    ("RECOGNISE_REGULAR_INTEREST_INCOME", "regular_interest_income_holding", "DEBIT", "Recognise regular interest income", "EVENT"),
    ("RECOGNISE_REGULAR_INTEREST_INCOME", "regular_interest_income", "CREDIT", "Recognise regular interest income", "EVENT"),
    ("REVERSAL_REGULAR_INTEREST_ACCRUAL", "regular_interest_income_holding", "DEBIT", "Reversal of regular interest accrual", "EVENT"),
    ("REVERSAL_REGULAR_INTEREST_ACCRUAL", "regular_interest_accrued", "CREDIT", "Reversal of regular interest accrual", "EVENT"),
    ("PROVISION_RAISE", "impairment_loss_expense", "DEBIT", "Raising a provision (increasing risk)", "EOM"),
    ("PROVISION_RAISE", "allowance_credit_losses", "CREDIT", "Raising a provision (increasing risk)", "EOM"),
    ("PROVISION_REVERSAL", "allowance_credit_losses", "DEBIT", "Reversing a provision (quality improves)", "EOM"),
    ("PROVISION_REVERSAL", "impairment_loss_expense", "CREDIT", "Reversing a provision (quality improves)", "EOM"),
    ("PRINCIPAL_WRITEOFF", "allowance_credit_losses", "DEBIT", "Principal write-off (final loss)", "EVENT"),
    ("PRINCIPAL_WRITEOFF", "loan_principal", "CREDIT", "Principal write-off (final loss)", "EVENT"),
    ("INTEREST_WRITEOFF", "bad_debts_expense", "DEBIT", "Interest write-off (no suspense balance)", "EVENT"),
    ("INTEREST_WRITEOFF", "regular_interest_arrears", "CREDIT", "Interest write-off (no suspense balance)", "EVENT"),
    ("WRITEOFF_RECOVERY", "cash_operating", "DEBIT", "Receipt from a fully written-off loan", "EVENT"),
    ("WRITEOFF_RECOVERY", "bad_debts_recovered", "CREDIT", "Receipt from a fully written-off loan", "EVENT"),
    ("LOAN_RESTRUCTURE_CAPITALISE", "loan_principal", "DEBIT", "Capitalisation of interest and arrears (restructure)", "EVENT"),
    ("LOAN_RESTRUCTURE_CAPITALISE", "principal_arrears", "CREDIT", "Capitalisation of principal arrears (restructure)", "EVENT"),
    ("LOAN_RESTRUCTURE_CAPITALISE", "regular_interest_arrears", "CREDIT", "Capitalisation of regular interest arrears (restructure)", "EVENT"),
    ("LOAN_RESTRUCTURE_CAPITALISE", "penalty_interest_asset", "CREDIT", "Capitalisation of penalty interest (restructure)", "EVENT"),
    ("LOAN_RESTRUCTURE_CAPITALISE", "default_interest_asset", "CREDIT", "Capitalisation of default interest (restructure)", "EVENT"),
    ("LOAN_RESTRUCTURE_CAPITALISE", "fees_charges_arrears", "CREDIT", "Capitalisation of fees and charges arrears (restructure)", "EVENT"),
    ("RESTRUCTURE_FEE_CHARGE", "loan_principal", "DEBIT", "Restructure fee (charged to customer)", "EVENT"),
    ("RESTRUCTURE_FEE_CHARGE", "deferred_fee_liability", "CREDIT", "Restructure fee (deferred)", "EVENT"),
    ("RESTRUCTURE_FEE_AMORTISATION", "deferred_fee_liability", "DEBIT", "Restructure fee amortisation (monthly)", "EOM"),
    ("RESTRUCTURE_FEE_AMORTISATION", "deferred_fee_income", "CREDIT", "Restructure fee amortisation (monthly)", "EOM"),
    ("PASS_THROUGH_COST_DISBURSEMENT", "deferred_fee_commission_asset", "DEBIT", "Payment of third-party cost (pass-through)", "EVENT"),
    ("PASS_THROUGH_COST_DISBURSEMENT", "cash_operating", "CREDIT", "Payment of third-party cost (pass-through)", "EVENT"),
    ("PASS_THROUGH_COST_RECOVERY", "cash_operating", "DEBIT", "Receipt of pass-through costs (recovery)", "EVENT"),
    ("PASS_THROUGH_COST_RECOVERY", "deferred_fee_commission_asset", "CREDIT", "Receipt of pass-through costs (recovery)", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_PASS_THROUGH_COST_RECOVERY", "unapplied_funds", "DEBIT", "Unapplied liquidation: fees/charges (recovery)", "EVENT"),
    ("UNAPPLIED_LIQUIDATION_PASS_THROUGH_COST_RECOVERY", "deferred_fee_commission_asset", "CREDIT", "Unapplied liquidation: fees/charges (recovery)", "EVENT"),
    ("UNAPPLIED_FUNDS_OVERPAYMENT", "cash_operating", "DEBIT", "Unapplied funds — customer overpayment (receipt)", "EVENT"),
    ("UNAPPLIED_FUNDS_OVERPAYMENT", "unapplied_funds", "CREDIT", "Unapplied funds — customer overpayment (receipt)", "EVENT"),
    ("FEES_CHARGES_WRITEOFF", "allowance_credit_losses", "DEBIT", "Fees and charges arrears write-off (final loss)", "EVENT"),
    ("FEES_CHARGES_WRITEOFF", "fees_charges_arrears", "CREDIT", "Fees and charges arrears write-off (final loss)", "EVENT"),
    ("AGENT_COMMISSION_PAYMENT", "fees_commission_expense", "DEBIT", "Payment of agent commission", "EVENT"),
    ("AGENT_COMMISSION_PAYMENT", "cash_operating", "CREDIT", "Payment of agent commission", "EVENT"),
    ("COMMISSION_AMORTISATION", "fees_commission_expense", "DEBIT", "Monthly amortisation of commission", "EOM"),
    ("COMMISSION_AMORTISATION", "deferred_fee_commission_asset", "CREDIT", "Monthly amortisation of commission", "EOM"),
    ("BORROWING_DRAWDOWN", "cash_operating", "DEBIT", "Drawdown on a borrowing from a Financier", "EVENT"),
    ("BORROWING_DRAWDOWN", "deferred_fee_asset_borrowings", "DEBIT", "Drawdown on a borrowing from a Financier - fees paid", "EVENT"),
    ("BORROWING_DRAWDOWN", "borrowings_loan_principal", "CREDIT", "Drawdown on a borrowing from a Financier - principal owed", "EVENT"),
    ("INTEREST_EXPENSE_ACCRUAL", "interest_expense", "DEBIT", "Monthly Accrual of interest expense", "EOM"),
    ("INTEREST_EXPENSE_ACCRUAL", "interest_payable", "CREDIT", "Monthly Accrual of interest expense", "EOM"),
    ("BORROWING_FEES_AMORTISATION", "amortization_borrowing_fees", "DEBIT", "Amortization of Loan Fees", "EOM"),
    ("BORROWING_FEES_AMORTISATION", "deferred_fee_asset_borrowings", "CREDIT", "Amortization of Loan Fees", "EOM"),
    ("BORROWING_REPAYMENT", "borrowings_loan_principal", "DEBIT", "Payment of borrowings", "EVENT"),
    ("BORROWING_REPAYMENT", "interest_payable", "DEBIT", "Payment of borrowings - interest component", "EVENT"),
    ("BORROWING_REPAYMENT", "cash_operating", "CREDIT", "Payment of borrowings - cash outflow", "EVENT"),
]

# (code, name, category, system_tag, parent_code) — same order as seed_accounting.ACCOUNTS
CHART_ACCOUNT_TUPLES: list[tuple[str, str, str, str | None, str | None]] = [
    ("A100000", "CASH AND CASH EQUIVALENTS", "ASSET", None, None),
    ("A100001", "BANK - MAIN OPERATING ACCOUNT", "ASSET", "cash_operating", "A100000"),
    ("A100002", "PETTY CASH", "ASSET", "petty_cash", "A100000"),
    ("A110000", "CUSTOMER LOAN PORTFOLIO (PRINCIPAL)", "ASSET", None, None),
    ("A110001", "PRINCIPAL - NOT YET DUE", "ASSET", "loan_principal", "A110000"),
    ("A110002", "PRINCIPAL ARREARS", "ASSET", "principal_arrears", "A110000"),
    ("A120000", "LOAN INTEREST & FEES RECEIVABLE", "ASSET", None, None),
    ("A120001", "REGULAR INTEREST ACCRUED (UNBILLED)", "ASSET", "regular_interest_accrued", "A120000"),
    ("A120002", "REGULAR INTEREST ARREARS", "ASSET", "regular_interest_arrears", "A120000"),
    ("A120003", "PENALTY INTEREST ASSET", "ASSET", "penalty_interest_asset", "A120000"),
    ("A120004", "DEFAULT INTEREST ASSET", "ASSET", "default_interest_asset", "A120000"),
    ("A120005", "FEES AND CHARGES ARREARS", "ASSET", "fees_charges_arrears", "A120000"),
    ("A130000", "PORTFOLIO CONTRA-ASSETS (PROVISION)", "ASSET", None, None),
    ("A130001", "ALLOWANCE FOR CREDIT LOSSES", "ASSET", "allowance_credit_losses", "A130000"),
    ("A130002", "PENALTY INTEREST IN SUSPENSE", "ASSET", "penalty_interest_suspense", "A130000"),
    ("A130003", "DEFAULT INTEREST IN SUSPENSE", "ASSET", "default_interest_suspense", "A130000"),
    ("A130004", "REGULAR INTEREST IN SUSPENSE", "ASSET", "regular_interest_suspense", "A130000"),
    ("A140000", "FIXED & OTHER ASSETS", "ASSET", None, None),
    ("A140001", "FIXED ASSETS - COST", "ASSET", "fixed_assets_cost", "A140000"),
    ("A140002", "ACCUMULATED DEPRECIATION", "ASSET", "accumulated_depreciation", "A140000"),
    ("A140003", "DEFERRED FEE AND COMMISSION ASSET", "ASSET", "deferred_fee_commission_asset", "A140000"),
    ("A150000", "DEFERRED BORROWING COSTS", "ASSET", None, None),
    ("A150001", "DEFERRED FEE ASSET (BORROWINGS)", "ASSET", "deferred_fee_asset_borrowings", "A150000"),
    ("L200000", "CUSTOMER & SHORT-TERM LIABILITIES", "LIABILITY", None, None),
    ("L200001", "DEFERRED FEE LIABILITY", "LIABILITY", "deferred_fee_liability", "L200000"),
    ("L200002", "REGULAR INTEREST INCOME HOLDING", "LIABILITY", "regular_interest_income_holding", "L200000"),
    ("L210000", "BORROWINGS & EXTERNAL DEBT", "LIABILITY", None, None),
    ("L210001", "BORROWINGS - LOAN PRINCIPAL", "LIABILITY", "borrowings_loan_principal", "L210000"),
    ("L210002", "INTEREST PAYABLE", "LIABILITY", "interest_payable", "L210000"),
    ("L220000", "OPERATIONAL LIABILITIES", "LIABILITY", None, None),
    ("L220001", "ACCOUNTS PAYABLE", "LIABILITY", "accounts_payable", "L220000"),
    ("L220002", "ACCRUED EXPENSES", "LIABILITY", "accrued_expenses", "L220000"),
    ("L220003", "TAX LIABILITY", "LIABILITY", "tax_liability", "L220000"),
    ("L220004", "UNAPPLIED FUNDS (OVERPAYMENTS)", "LIABILITY", "unapplied_funds", "L220000"),
    ("C300000", "EQUITY AND CAPITAL", "EQUITY", None, None),
    ("C300001", "SHARE CAPITAL", "EQUITY", "share_capital", "C300000"),
    ("C300002", "SHARE PREMIUM", "EQUITY", "share_premium", "C300000"),
    ("C300003", "RETAINED EARNINGS", "EQUITY", "retained_earnings", "C300000"),
    ("C300004", "DIVIDENDS PAID", "EQUITY", "dividends_paid", "C300000"),
    ("R400000", "LENDING INCOME (REVENUE)", "INCOME", None, None),
    ("R400001", "REGULAR INTEREST INCOME", "INCOME", "regular_interest_income", "R400000"),
    ("R400002", "DEFERRED FEE INCOME", "INCOME", "deferred_fee_income", "R400000"),
    ("R400003", "PENALTY INTEREST INCOME", "INCOME", "penalty_interest_income", "R400000"),
    ("R400004", "DEFAULT INTEREST INCOME", "INCOME", "default_interest_income", "R400000"),
    ("R400005", "BAD DEBTS RECOVERED", "INCOME", "bad_debts_recovered", "R400000"),
    ("E500000", "FINANCIAL & LENDING EXPENSES", "EXPENSE", None, None),
    ("E500001", "INTEREST EXPENSE", "EXPENSE", "interest_expense", "E500000"),
    ("E500002", "IMPAIRMENT LOSS EXPENSE", "EXPENSE", "impairment_loss_expense", "E500000"),
    ("E500003", "BAD DEBTS EXPENSE", "EXPENSE", "bad_debts_expense", "E500000"),
    ("E500004", "FEES AND COMMISSION EXPENSE", "EXPENSE", "fees_commission_expense", "E500000"),
    ("E500005", "AMORTIZATION OF BORROWING FEES", "EXPENSE", "amortization_borrowing_fees", "E500000"),
    ("E510000", "ADMINISTRATIVE EXPENSES", "EXPENSE", None, None),
    ("E510001", "STAFF COSTS", "EXPENSE", "staff_costs", "E510000"),
    ("E510002", "PREMISES & UTILITIES", "EXPENSE", "premises_utilities", "E510000"),
    ("E510003", "COMMUNICATION & IT", "EXPENSE", "communication_it", "E510000"),
    ("E510004", "DEPRECIATION EXPENSE", "EXPENSE", "depreciation_expense", "E510000"),
    ("E510005", "TRAVEL & MOTOR", "EXPENSE", "travel_motor", "E510000"),
    ("E510006", "PROFESSIONAL FEES", "EXPENSE", "professional_fees", "E510000"),
    ("E510007", "OFFICE ADMIN", "EXPENSE", "office_admin", "E510000"),
    ("E510008", "MARKETING", "EXPENSE", "marketing", "E510000"),
]


def build_receipt_gl_mapping_tuples() -> list[tuple[str, str, str, str, int, int]]:
    """(trigger_source, allocation_key, event_type, amount_source, amount_sign, priority)."""
    originals = [
        ("alloc_principal_arrears", "PAYMENT_PRINCIPAL"),
        ("alloc_principal_not_due", "PAYMENT_PRINCIPAL_NOT_YET_DUE"),
        ("alloc_interest_arrears", "PAYMENT_REGULAR_INTEREST"),
        ("alloc_interest_accrued", "PAYMENT_REGULAR_INTEREST_NOT_YET_DUE"),
        ("alloc_penalty_interest", "PAYMENT_PENALTY_INTEREST"),
        ("alloc_default_interest", "PAYMENT_DEFAULT_INTEREST"),
        ("alloc_regular_interest", "PAYMENT_REGULAR_INTEREST_SUSPENSE"),
        ("alloc_regular_interest", "PAYMENT_REGULAR_INTEREST_ACCRUED"),
        ("alloc_fees_charges", "PASS_THROUGH_COST_RECOVERY"),
    ]
    rows: list[tuple[str, str, str, str, int, int]] = []
    for i, (alloc_key, evt) in enumerate(originals):
        rows.append(("SAVE_RECEIPT", alloc_key, evt, alloc_key, 1, 10 + i))
    for i, (alloc_key, evt) in enumerate(originals):
        rows.append(("SAVE_REVERSAL", alloc_key, evt, alloc_key, -1, 100 + i))
    for i, (alloc_key, evt) in enumerate(originals):
        rows.append(("APPLY_UNAPPLIED", alloc_key, evt, alloc_key, 1, 200 + i))
    return rows
