CREATE TABLE IF NOT EXISTS document_categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS documents (
    id SERIAL PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id INTEGER NOT NULL,
    category_id INTEGER REFERENCES document_categories(id),
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(100) NOT NULL,
    file_size INTEGER NOT NULL,
    file_content BYTEA NOT NULL,
    uploaded_by VARCHAR(255),
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_documents_entity ON documents(entity_type, entity_id);

INSERT INTO document_categories (name, description) VALUES
('National ID', 'National Identification Document'),
('Proof of Residence', 'Utility bill or similar proof of address'),
('Bank Statement', 'Bank statement for financial assessment'),
('Payslip', 'Recent payslip'),
('Signed Loan Agreement', 'Signed agreement document'),
('Offer Letter', 'Autogenerated offer letter')
ON CONFLICT (name) DO NOTHING;
