#!/usr/bin/env python3
"""
Create .streamlit/secrets.toml from config.py DB settings if the file does not exist.

SQLAlchemy tenant modules read st.secrets['postgres']; this aligns them with FARNDACRED_* env.

Run from repo root:

    python scripts/bootstrap_streamlit_secrets_from_config.py

Does not overwrite an existing secrets.toml (delete it first to regenerate).
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import config


def main() -> int:
    target = ROOT / ".streamlit" / "secrets.toml"
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        print(f"Already exists (not overwriting): {target}")
        return 0

    port = int(config.DB_PORT) if str(config.DB_PORT).isdigit() else 5432
    # Escape double quotes in password for TOML basic string
    pw = (config.DB_PASSWORD or "").replace("\\", "\\\\").replace('"', '\\"')

    body = (
        "# Generated by scripts/bootstrap_streamlit_secrets_from_config.py\n"
        "# Tenant resolver (optional)\n"
        "[tenant]\n"
        'default_company_name = "Farnda Demo"\n\n'
        "[postgres]\n"
        f'host = "{config.DB_HOST}"\n'
        f"port = {port}\n"
        f'user = "{config.DB_USER}"\n'
        f'password = "{pw}"\n'
        f'database = "{config.DB_NAME}"\n'
    )
    target.write_text(body, encoding="utf-8")
    print(f"Wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
